<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title> Welcome to Wybe </title>

	<style type="text/css">
	body {
		width: 100%;
		color: #333;
		font-family: 'Lucida Sans Unicode','Lucida Grande','Lucida Sans','DejaVu Sans Condensed',sans-serif;
	}
	article {
		width: 960px;
		margin: 0 auto;
	}
	h1, h2 {
		color: #666;
		font-family:Constantina,Georgia,'Nimbus Roman No9 L',serif;
	}
	</style>
</head>
<body>

<article>
	<h1> <?= $this->title ?> </h1>
	<p>This is an example profile.</p>
</article>

</body>
</html>